### PR TITLE
New model and improved testing

### LINKED ISSUE #13: Retrain model for G1 and G2
Take out age and replace with G1 and G2 scores. These are more representative of actual criteria and will prob increase the rating of accuracy

### LINKED ISSUE #14: New tests for new model predictors
Becuase we are no longer using age and helath to predict, our tests will not work.
The tests must be changed to take G1, G2 and studytime in order to account for the new predictors.

NOTE: We still want to test status codes

### LINKED ISSUE #16: Update ReadMe to better describe new feature used to train model
Create a ReadMe that describes the choices of features used to train the model and the improvements in the performance.

### PR DESCRIPTION
**Pull request by carsonstuart**
- Added G1 and G2 to the ML model. (improved accuracy to 99%)
- Changed testing to reflect this change.
- Added additional tests to ensure all edge cases are covered.
- Resolves #13 and #14

### CODE REVIEW

**Review by rmartini24 — APPROVED** [review]
LGTM, good work.

**Review by whuang1202 — APPROVED** [review]
nice

**Review by liusteph — APPROVED** [review]
LGTM

**Review by n8thanwai — APPROVED** [review]
LGTM

**Pull request merged**
