### PR TITLE
Resolves #15 by updating the model with valid inputs and #16 by adding a readme describing the newly trained model

### LINKED ISSUE #15: Make validations for inputs and return status code on inputs
If the user inputs an input value that does not match what the value should be (non-negative and number) then we want to return a status code for that error.

### LINKED ISSUE #16: Update ReadMe to better describe new feature used to train model
Create a ReadMe that describes the choices of features used to train the model and the improvements in the performance.

### PR DESCRIPTION
**Pull request by whuang1202**
Updated the model with a new readme describing how we use G1/G2/absences/study time are good factors for determining student success.

### CODE REVIEW

**Comment by whuang1202** [comment]
Also updated the models by checking for sane input (integer input that is non-negative) for all the values we are checking for, which makes it so that incorrect input raises an error code

**Review by rmartini24 — APPROVED** [review]
LGTM

**Review by n8thanwai — APPROVED** [review]
LGTM

**Review by carsonstuart — APPROVED** [review]
looks good willy

**Review by liusteph — APPROVED** [review]
LGTM

**Pull request merged**
